//@Casucci Leonardo 2073980

#ifndef EVENT_TYPE_H
#define EVENT_TYPE_H

enum EventType {
    PASSAGGIO_VIA, TIRO_DADI, ARRIVO, ACQUISTO_TERRENO,
    COSTRUZIONE_CASA, COSTRUZIONE_ALBERGO,
    PAGAMENTO_PERNOTTAMENTO, SHOW_COMMAND, FINE_TURNO,
    ELIMINAZIONE, VITTORIA
};

#endif